# NumPy

## Numpy Arrays

NumPy is a Linear Algebra library for Python.  
Multiple other python libs used for data analysis & ML are dependent on NumPy, hence making it extremely popular.  

numpy arrays come in 2 flavours - vectors(1-d) and matrices(2-d)

In [2]:
import numpy as np

In [3]:
# Get np array from py objects

arr = np.array([1,2,3])
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [4]:
print(arr)
print(mat)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
arr

array([1, 2, 3])

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print(type(arr))
print(type(mat))  # type is numpy.ndarray

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
# How to quickly generate np arrays

In [8]:
np.arange(0, 10)   # Like python's range() func

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)  # step size of 2

array([0, 2, 4, 6, 8])

In [13]:
# Get an np array of zeros
# Useful to initialize arrays
np.zeros(3)  # 1-d array of size 3

array([0., 0., 0.])

In [16]:
np.zeros((3,4))  # matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [17]:
# Linearly(evenly) spaced numbers b/w a range

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,9,10) # inclusive of 0 and 9

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
# Identity matrix !!!!! 
# These are pretty useful in linear algebra

np.eye(5)  # size of matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# What about arrays with random numbers in a range i.e. uniformly distributed numbers in a range

np.random.rand(5)   # 5 numbers between 0 and 1

array([0.96872984, 0.84772021, 0.68542197, 0.00898501, 0.83418382])

In [24]:
np.random.rand(3,4) 

array([[0.90716142, 0.75524024, 0.59433257, 0.7309051 ],
       [0.04328907, 0.92126153, 0.72947048, 0.88492418],
       [0.56879922, 0.07011309, 0.68889677, 0.98608367]])

In [26]:
# Normal distribution

np.random.randn(5)  # What is the mean and standard deviation for normal dist ??

array([ 0.53036224, -0.27048706,  0.16420849, -0.44226521,  1.16013668])

In [27]:
np.random.randint(1, 100)  # including 1 and excluding 100

25

In [28]:
np.random.randint(1, 100, 10) # 10 random int

array([54, 41,  8, 71, 19, 34, 12, 29, 74, 99])

## Some useful methods on nd arrays

In [31]:
randarr = np.random.randint(1,100, 25)

In [32]:
randarr

array([65, 23, 65, 92, 44, 19, 17, 39, 95, 39, 81, 33, 27, 73, 64,  3, 91,
       65, 36, 95, 46, 94, 86,  6, 89])

In [34]:
randarr.reshape(5,5)  # reshapes the 1-d array into 2-d array

array([[65, 23, 65, 92, 44],
       [19, 17, 39, 95, 39],
       [81, 33, 27, 73, 64],
       [ 3, 91, 65, 36, 95],
       [46, 94, 86,  6, 89]])

In [35]:
randarr.min()

3

In [36]:
randarr.max()

95

In [37]:
randarr.argmax()  # Gives the index(starting 0) of the max element

8

In [44]:
randarr[randarr.argmax()]

95

In [38]:
randarr.argmin()

15

In [40]:
# dimentions of nd array

randarr.shape

(25,)

In [41]:
randarr.reshape(5,5).shape

(5, 5)

In [42]:
randarr.dtype

dtype('int64')