# NumPy - Indexing and Selection

## 1-d arrays

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]

4

In [6]:
arr[4:9]  # slicing and indexing like python lists

array([4, 5, 6, 7, 8])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:3] = 100   # broadcasts 100 to indices 0,1,2 i.e. exclusive 3

In [9]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [10]:
# python lists have this ?
my_list = range(0,11)

In [11]:
my_list[0:3] = 100 # range object doesn't support this but np.darray supports broadcasting

TypeError: 'range' object does not support item assignment

In [12]:
# reset array
arr = np.arange(0,11)

In [13]:
# Slicing np.darrays

slice_of_arr = arr[0:5]
slice_of_arr[:] = 99
slice_of_arr  # all elements of slice_of_arr should be 99

array([99, 99, 99, 99, 99])

In [14]:
# What about the original array arr
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [16]:
# Those elements are also changed.
# Thus, elements in slice_of_arr are just pointers to the original arr. Changing one changes the other
# NumPy does this for efficient memory management for large arrays

> Slicing np.ndarray creates a pointer to the elements of the original array and NOT a copy of the elements

In [18]:
# How to actually copy the array ?

arr = np.arange(0,11)
slice_of_arr_copy = arr[:5].copy()

In [19]:
slice_of_arr_copy

array([0, 1, 2, 3, 4])

In [20]:
slice_of_arr_copy[:] = 98
slice_of_arr_copy

array([98, 98, 98, 98, 98])

In [21]:
arr  # original array is uneffected

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
type(arr)

numpy.ndarray

## 2-d arrays

In [25]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [26]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
# Selecting one element

arr_2d[0][1]  # row 0, col 1

10

In [28]:
arr_2d[0]  # row 0

array([ 5, 10, 15])

In [29]:
type(arr_2d[0])

numpy.ndarray

In [32]:
print(arr_2d[0][1])  # double bracket notation
print(arr_2d[0,1])   # comma notation. More readable

10
10


In [33]:
# Slicing 2-d array

arr_2d[:2, 1:]   # row indices: 0,1 ; col indices: 1 to end
                 # follows the slicing rules of python lists

array([[10, 15],
       [25, 30]])

In [34]:
# slice rows
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
# slice cols
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

> Slicing and selecting elements of np.ndarray is soooo convenient !!

## Filtering np.ndarrays

In [36]:
arr = np.arange(0,11)

In [40]:
arr > 5  # applies the filter to each element in the array and returns np.ndarray of True & False 
         # of length equal to the length of arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [38]:
bool_arr = arr > 5
type(bool_arr)

numpy.ndarray

In [39]:
bool_arr.dtype  # boolean type

dtype('bool')

In [41]:
# How is a boolean array useful ?
# We can use a boolean array to filter the elements of the np.ndarray

arr[bool_arr]  # Elements for which corresponding elements are true is returned

array([ 6,  7,  8,  9, 10])

In [45]:
# Lets fitler using a bool array with all true values

np.ones(11, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[np.ones(11, dtype=bool)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

> Commonly used filtering notation: `arr[arr > 5]`