# NumPy Operations

* Array with array
* Array with Scalars
* Universal array functions

In [1]:
import numpy as np

## Operating with 2 arrays of same size

In [2]:
arr = np.arange(0,11)

In [3]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr + np.ones(11, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Array and a scalar

In [9]:
arr + 100   # broadcasts the scalar quantity to each element of the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

---

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr/arr

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Notice the element is `nan`. The first operation is `0/0` which generally in python would have given an Error. 
But numpy generates an `nan` and a warning, instead of an error.  

Keep this in mind while operating on arrays.

In [12]:
1 / arr

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

Here, `1/0` gave `inf` and a warning.

In [13]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## np.ndarray functions

These are called in functional style -  
`np.func(ndarray)`  

func = min, max, sqrt, exp, sin, log etc. etc.

These functions are called [Universal functions(ufunc)](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

> Most common mathematical operations are provided as Universa functions by numpy